name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Black and Ruff
        run: |
          python -m pip install --upgrade pip
          pip install black ruff
      - name: Run Black (style check)
        run: black --check .
      - name: Run Ruff (lint)
        run: ruff .
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: pnpm
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install frontend dependencies and lint
        run: |
          cd frontend
          pnpm install
          pnpm lint

  backend-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run pytest with coverage
        run: pytest --maxfail=1 --disable-warnings --cov=backend --cov-report=xml

  frontend-tests:
    runs-on: ubuntu-latest
    needs: backend-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: pnpm
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: |
          cd frontend
          pnpm install
      - name: Run frontend unit tests
        run: |
          cd frontend
          pnpm test -- --coverage

  frontend-build:
    runs-on: ubuntu-latest
    needs: frontend-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: pnpm
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install and build frontend
        run: |
          cd frontend
          pnpm install
          pnpm build

  docker-build:
    runs-on: ubuntu-latest
    needs: frontend-build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Backend Docker Image
        run: |
          docker build --no-cache -t claims-ai-backend:latest -f backend/Dockerfile .
      - name: Log into GitHub Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Publish Backend Image to GHCR
        run: |
          docker tag claims-ai-backend:latest ghcr.io/${{ github.repository }}/claims-ai-backend:latest
          docker push ghcr.io/${{ github.repository }}/claims-ai-backend:latest
      - name: Build Frontend Docker Image
        run: docker build --no-cache -t claims-ai-frontend:latest -f frontend/Dockerfile frontend
      - name: Publish Frontend Image to GHCR
        run: |
          docker tag claims-ai-frontend:latest ghcr.io/${{ github.repository }}/claims-ai-frontend:latest
          docker push ghcr.io/${{ github.repository }}/claims-ai-frontend:latest 